name: didit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_animate: ^4.5.0
  intl: ^0.20.2
  google_mobile_ads: ^7.0.0
  tutorial_coach_mark: ^1.3.3
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  icloud_storage: ^2.0.0
  path_provider: 2.1.2
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  package_info_plus: ^9.0.0

dependency_overrides:
  path_provider_foundation: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
